# Generated by Django 5.1.1 on 2024-09-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('question1', models.CharField(max_length=11)),
                ('question2', models.CharField(max_length=11)),
                ('question3', models.CharField(max_length=11)),
                ('question4', models.CharField(max_length=11)),
                ('question5a', models.CharField(max_length=11)),
                ('question5b', models.CharField(max_length=11)),
                ('question5c', models.CharField(max_length=11)),
                ('question5d', models.CharField(max_length=11)),
                ('question5e', models.CharField(max_length=11)),
                ('question5f', models.CharField(max_length=11)),
                ('question5g', models.CharField(max_length=11)),
                ('question5h', models.CharField(max_length=11)),
                ('question5i', models.CharField(max_length=11)),
                ('question5j', models.CharField(blank=True, max_length=11, null=True)),
                ('question6', models.CharField(max_length=11)),
                ('question7', models.CharField(max_length=11)),
                ('question8', models.CharField(max_length=11)),
                ('question9', models.CharField(max_length=11)),
            ],
        ),
    ]
