# Generated by Django 5.1.1 on 2024-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='question5jTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
