# Generated by Django 5.1.1 on 2024-09-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_question5jtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='question1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5e',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5f',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5g',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5i',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question5j',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='question6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question9',
            field=models.IntegerField(),
        ),
    ]
