# Generated by Django 5.1.1 on 2024-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_form_question1_alter_form_question2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='question1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='question3',
            field=models.TimeField(),
        ),
    ]
